# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/uifiles/registrydecoder.ui'
#
# Created: Fri Oct  7 13:42:05 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_registrydecoder(object):
    def setupUi(self, registrydecoder):
        registrydecoder.setObjectName("registrydecoder")
        registrydecoder.resize(1197, 877)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(registrydecoder.sizePolicy().hasHeightForWidth())
        registrydecoder.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(registrydecoder)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_10 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem = QtGui.QSpacerItem(20, 253, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(414, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtGui.QLabel(self.page_4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 2)
        self.startnewcase = QtGui.QRadioButton(self.page_4)
        self.startnewcase.setChecked(True)
        self.startnewcase.setObjectName("startnewcase")
        self.gridLayout_9.addWidget(self.startnewcase, 2, 0, 1, 1)
        self.loadexisting = QtGui.QRadioButton(self.page_4)
        self.loadexisting.setObjectName("loadexisting")
        self.gridLayout_9.addWidget(self.loadexisting, 2, 1, 1, 1)
        self.startPageButton = QtGui.QPushButton(self.page_4)
        self.startPageButton.setObjectName("startPageButton")
        self.gridLayout_9.addWidget(self.startPageButton, 4, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 1, 1, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(414, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 1, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 253, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem5, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_12 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem6 = QtGui.QSpacerItem(20, 322, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(407, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem7, 1, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.caseFolderInput = QtGui.QLineEdit(self.page_6)
        self.caseFolderInput.setObjectName("caseFolderInput")
        self.gridLayout_11.addWidget(self.caseFolderInput, 2, 0, 1, 3)
        self.loadCaseButton = QtGui.QPushButton(self.page_6)
        self.loadCaseButton.setObjectName("loadCaseButton")
        self.gridLayout_11.addWidget(self.loadCaseButton, 4, 0, 1, 1)
        self.goBackPushButton = QtGui.QPushButton(self.page_6)
        self.goBackPushButton.setObjectName("goBackPushButton")
        self.gridLayout_11.addWidget(self.goBackPushButton, 4, 1, 1, 1)
        self.browseCaseButton = QtGui.QPushButton(self.page_6)
        self.browseCaseButton.setObjectName("browseCaseButton")
        self.gridLayout_11.addWidget(self.browseCaseButton, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 1, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(407, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem8, 1, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 321, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem9, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_14 = QtGui.QGridLayout(self.page)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem10 = QtGui.QSpacerItem(20, 168, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(386, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem11, 1, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout_13.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.casename = QtGui.QLineEdit(self.page)
        self.casename.setMaximumSize(QtCore.QSize(250, 100))
        self.casename.setObjectName("casename")
        self.gridLayout_7.addWidget(self.casename, 0, 0, 1, 1)
        self.casenumber = QtGui.QLineEdit(self.page)
        self.casenumber.setMaximumSize(QtCore.QSize(250, 100))
        self.casenumber.setObjectName("casenumber")
        self.gridLayout_7.addWidget(self.casenumber, 2, 0, 1, 1)
        self.investigatorname = QtGui.QLineEdit(self.page)
        self.investigatorname.setMaximumSize(QtCore.QSize(250, 100))
        self.investigatorname.setObjectName("investigatorname")
        self.gridLayout_7.addWidget(self.investigatorname, 4, 0, 1, 1)
        self.comments = QtGui.QLineEdit(self.page)
        self.comments.setMaximumSize(QtCore.QSize(250, 100))
        self.comments.setObjectName("comments")
        self.gridLayout_7.addWidget(self.comments, 6, 0, 1, 1)
        self.caseDirectoryInput = QtGui.QLineEdit(self.page)
        self.caseDirectoryInput.setMaximumSize(QtCore.QSize(250, 100))
        self.caseDirectoryInput.setObjectName("caseDirectoryInput")
        self.gridLayout_7.addWidget(self.caseDirectoryInput, 8, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem12, 1, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem13, 3, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem14, 5, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem15, 7, 0, 1, 1)
        self.BrowseCreateCase = QtGui.QPushButton(self.page)
        self.BrowseCreateCase.setObjectName("BrowseCreateCase")
        self.gridLayout_7.addWidget(self.BrowseCreateCase, 8, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_7, 0, 1, 1, 2)
        self.caseInformationButton = QtGui.QPushButton(self.page)
        self.caseInformationButton.setMaximumSize(QtCore.QSize(250, 250))
        self.caseInformationButton.setObjectName("caseInformationButton")
        self.gridLayout_13.addWidget(self.caseInformationButton, 2, 1, 1, 1)
        self.goBackPushButton2 = QtGui.QPushButton(self.page)
        self.goBackPushButton2.setObjectName("goBackPushButton2")
        self.gridLayout_13.addWidget(self.goBackPushButton2, 2, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem16, 1, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 1, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(386, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem17, 1, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 167, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem18, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.add_evidence_page = QtGui.QWidget()
        self.add_evidence_page.setObjectName("add_evidence_page")
        self.gridLayout_16 = QtGui.QGridLayout(self.add_evidence_page)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setSpacing(30)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.evidenceTable = QtGui.QTableWidget(self.add_evidence_page)
        self.evidenceTable.setObjectName("evidenceTable")
        self.evidenceTable.setColumnCount(0)
        self.evidenceTable.setRowCount(0)
        self.gridLayout_15.addWidget(self.evidenceTable, 0, 0, 1, 4)
        self.label_7 = QtGui.QLabel(self.add_evidence_page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_15.addWidget(self.label_7, 1, 0, 1, 1)
        self.currentCheckBox = QtGui.QCheckBox(self.add_evidence_page)
        self.currentCheckBox.setChecked(True)
        self.currentCheckBox.setObjectName("currentCheckBox")
        self.gridLayout_15.addWidget(self.currentCheckBox, 1, 1, 1, 1)
        self.backupCheckBox = QtGui.QCheckBox(self.add_evidence_page)
        self.backupCheckBox.setChecked(True)
        self.backupCheckBox.setObjectName("backupCheckBox")
        self.gridLayout_15.addWidget(self.backupCheckBox, 1, 2, 1, 2)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem19, 2, 0, 1, 4)
        self.addEvidenceButton = QtGui.QPushButton(self.add_evidence_page)
        self.addEvidenceButton.setObjectName("addEvidenceButton")
        self.gridLayout_15.addWidget(self.addEvidenceButton, 5, 0, 1, 1)
        self.doneEvidenceButton = QtGui.QPushButton(self.add_evidence_page)
        self.doneEvidenceButton.setObjectName("doneEvidenceButton")
        self.gridLayout_15.addWidget(self.doneEvidenceButton, 5, 3, 1, 1)
        self.removeEvidenceButton = QtGui.QPushButton(self.add_evidence_page)
        self.removeEvidenceButton.setObjectName("removeEvidenceButton")
        self.gridLayout_15.addWidget(self.removeEvidenceButton, 5, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.add_evidence_page)
        self.case_summary_page = QtGui.QWidget()
        self.case_summary_page.setObjectName("case_summary_page")
        self.gridLayout_18 = QtGui.QGridLayout(self.case_summary_page)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_5 = QtGui.QLabel(self.case_summary_page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_17.addWidget(self.label_5, 0, 0, 1, 1)
        self.summaryLabel = QtGui.QLabel(self.case_summary_page)
        self.summaryLabel.setText("")
        self.summaryLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.summaryLabel.setWordWrap(True)
        self.summaryLabel.setObjectName("summaryLabel")
        self.gridLayout_17.addWidget(self.summaryLabel, 1, 0, 1, 3)
        self.startProcessingButton = QtGui.QPushButton(self.case_summary_page)
        self.startProcessingButton.setObjectName("startProcessingButton")
        self.gridLayout_17.addWidget(self.startProcessingButton, 2, 1, 1, 1)
        self.backToAddEvidenceButton = QtGui.QPushButton(self.case_summary_page)
        self.backToAddEvidenceButton.setObjectName("backToAddEvidenceButton")
        self.gridLayout_17.addWidget(self.backToAddEvidenceButton, 2, 2, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.case_summary_page)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.progressLabel = QtGui.QLabel(self.page_7)
        self.progressLabel.setGeometry(QtCore.QRect(10, 30, 1141, 751))
        self.progressLabel.setText("")
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.stackedWidget.addWidget(self.page_7)
        self.analysis_page = QtGui.QWidget()
        self.analysis_page.setObjectName("analysis_page")
        self.gridLayout_3 = QtGui.QGridLayout(self.analysis_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.analysisTabWidget = QtGui.QTabWidget(self.analysis_page)
        self.analysisTabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.analysisTabWidget.sizePolicy().hasHeightForWidth())
        self.analysisTabWidget.setSizePolicy(sizePolicy)
        self.analysisTabWidget.setTabsClosable(True)
        self.analysisTabWidget.setObjectName("analysisTabWidget")
        self.FileViewTab = QtGui.QWidget()
        self.FileViewTab.setObjectName("FileViewTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.FileViewTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fileTreeWidget = QtGui.QTreeWidget(self.FileViewTab)
        self.fileTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fileTreeWidget.setColumnCount(1)
        self.fileTreeWidget.setObjectName("fileTreeWidget")
        self.gridLayout_4.addWidget(self.fileTreeWidget, 0, 0, 1, 1)
        self.treeViewPushButton = QtGui.QPushButton(self.FileViewTab)
        self.treeViewPushButton.setObjectName("treeViewPushButton")
        self.gridLayout_4.addWidget(self.treeViewPushButton, 1, 0, 1, 1)
        self.analysisTabWidget.addTab(self.FileViewTab, "")
        self.SearchTab = QtGui.QWidget()
        self.SearchTab.setObjectName("SearchTab")
        self.gridLayout_21 = QtGui.QGridLayout(self.SearchTab)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.searchTreeWidget = QtGui.QTreeWidget(self.SearchTab)
        self.searchTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.searchTreeWidget.setObjectName("searchTreeWidget")
        self.gridLayout_8.addWidget(self.searchTreeWidget, 0, 0, 1, 1)
        self.searchDiffTreeWidget = QtGui.QTreeWidget(self.SearchTab)
        self.searchDiffTreeWidget.setObjectName("searchDiffTreeWidget")
        self.gridLayout_8.addWidget(self.searchDiffTreeWidget, 1, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_8, 0, 0, 3, 1)
        spacerItem20 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem20, 0, 1, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_13 = QtGui.QLabel(self.SearchTab)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 14, 2, 1, 1)
        self.searchPushButton = QtGui.QPushButton(self.SearchTab)
        self.searchPushButton.setObjectName("searchPushButton")
        self.gridLayout_6.addWidget(self.searchPushButton, 17, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.SearchTab)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 14, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.SearchTab)
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 14, 0, 1, 1)
        self.partialSearchRadioButton = QtGui.QRadioButton(self.SearchTab)
        self.partialSearchRadioButton.setObjectName("partialSearchRadioButton")
        self.gridLayout_6.addWidget(self.partialSearchRadioButton, 11, 2, 1, 1)
        self.exactSearchRadioButton = QtGui.QRadioButton(self.SearchTab)
        self.exactSearchRadioButton.setChecked(True)
        self.exactSearchRadioButton.setObjectName("exactSearchRadioButton")
        self.gridLayout_6.addWidget(self.exactSearchRadioButton, 11, 0, 1, 1)
        self.searchKeysCheckBox = QtGui.QCheckBox(self.SearchTab)
        self.searchKeysCheckBox.setChecked(True)
        self.searchKeysCheckBox.setObjectName("searchKeysCheckBox")
        self.gridLayout_6.addWidget(self.searchKeysCheckBox, 12, 0, 1, 1)
        self.searchNamesCheckBox = QtGui.QCheckBox(self.SearchTab)
        self.searchNamesCheckBox.setChecked(True)
        self.searchNamesCheckBox.setObjectName("searchNamesCheckBox")
        self.gridLayout_6.addWidget(self.searchNamesCheckBox, 12, 1, 1, 1)
        self.searchDataCheckBox = QtGui.QCheckBox(self.SearchTab)
        self.searchDataCheckBox.setChecked(True)
        self.searchDataCheckBox.setObjectName("searchDataCheckBox")
        self.gridLayout_6.addWidget(self.searchDataCheckBox, 12, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.SearchTab)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 4, 0, 1, 3)
        self.searchLineEdit = QtGui.QLineEdit(self.SearchTab)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.gridLayout_6.addWidget(self.searchLineEdit, 2, 0, 1, 3)
        self.searchTermsPushButton = QtGui.QPushButton(self.SearchTab)
        self.searchTermsPushButton.setObjectName("searchTermsPushButton")
        self.gridLayout_6.addWidget(self.searchTermsPushButton, 8, 2, 1, 1)
        self.searchTermsLineEdit = QtGui.QLineEdit(self.SearchTab)
        self.searchTermsLineEdit.setObjectName("searchTermsLineEdit")
        self.gridLayout_6.addWidget(self.searchTermsLineEdit, 8, 0, 1, 2)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem21, 9, 0, 1, 3)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem22, 3, 0, 1, 3)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem23, 10, 0, 1, 3)
        self.label_16 = QtGui.QLabel(self.SearchTab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 15, 0, 1, 1)
        self.searchStartDateLineEdit = QtGui.QLineEdit(self.SearchTab)
        self.searchStartDateLineEdit.setObjectName("searchStartDateLineEdit")
        self.gridLayout_6.addWidget(self.searchStartDateLineEdit, 15, 1, 1, 1)
        self.searchEndDateLlineEdit = QtGui.QLineEdit(self.SearchTab)
        self.searchEndDateLlineEdit.setObjectName("searchEndDateLlineEdit")
        self.gridLayout_6.addWidget(self.searchEndDateLlineEdit, 15, 2, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem24, 13, 0, 1, 3)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem25, 16, 0, 1, 3)
        self.performSearchDiffCheckBox = QtGui.QCheckBox(self.SearchTab)
        self.performSearchDiffCheckBox.setObjectName("performSearchDiffCheckBox")
        self.gridLayout_6.addWidget(self.performSearchDiffCheckBox, 17, 0, 1, 1)
        self.searchTermLabel = QtGui.QLabel(self.SearchTab)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        self.searchTermLabel.setFont(font)
        self.searchTermLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.searchTermLabel.setObjectName("searchTermLabel")
        self.gridLayout_6.addWidget(self.searchTermLabel, 1, 0, 1, 3)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem26, 0, 0, 1, 3)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem27, 18, 0, 1, 3)
        self.gridLayout_20.addLayout(self.gridLayout_6, 1, 1, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(368, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem28, 2, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.analysisTabWidget.addTab(self.SearchTab, "")
        self.PluginsTab = QtGui.QWidget()
        self.PluginsTab.setObjectName("PluginsTab")
        self.gridLayout_22 = QtGui.QGridLayout(self.PluginsTab)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pluginDiffTreeWidget = QtGui.QTreeWidget(self.PluginsTab)
        self.pluginDiffTreeWidget.setObjectName("pluginDiffTreeWidget")
        self.gridLayout_5.addWidget(self.pluginDiffTreeWidget, 2, 0, 1, 1)
        self.pluginFilestreeWidget = QtGui.QTreeWidget(self.PluginsTab)
        self.pluginFilestreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.pluginFilestreeWidget.setObjectName("pluginFilestreeWidget")
        self.gridLayout_5.addWidget(self.pluginFilestreeWidget, 1, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.PluginsTab)
        self.label_9.setMinimumSize(QtCore.QSize(150, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setMargin(10)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 2)
        self.hiveComboBox = QtGui.QComboBox(self.PluginsTab)
        self.hiveComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.hiveComboBox.setObjectName("hiveComboBox")
        self.gridLayout.addWidget(self.hiveComboBox, 1, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.PluginsTab)
        self.label_11.setMinimumSize(QtCore.QSize(150, 0))
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setMargin(10)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 2)
        self.pluginListWidget = QtGui.QListWidget(self.PluginsTab)
        self.pluginListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.pluginListWidget.setObjectName("pluginListWidget")
        self.gridLayout.addWidget(self.pluginListWidget, 3, 0, 1, 2)
        self.pluginDiffCheckBox = QtGui.QCheckBox(self.PluginsTab)
        self.pluginDiffCheckBox.setObjectName("pluginDiffCheckBox")
        self.gridLayout.addWidget(self.pluginDiffCheckBox, 4, 0, 1, 1)
        self.runPluginButton = QtGui.QPushButton(self.PluginsTab)
        self.runPluginButton.setMinimumSize(QtCore.QSize(300, 0))
        self.runPluginButton.setObjectName("runPluginButton")
        self.gridLayout.addWidget(self.runPluginButton, 4, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.analysisTabWidget.addTab(self.PluginsTab, "")
        self.gridLayout_3.addWidget(self.analysisTabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.analysis_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        registrydecoder.setCentralWidget(self.centralwidget)
        self.toolBar_1 = QtGui.QToolBar(registrydecoder)
        self.toolBar_1.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolBar_1.setObjectName("toolBar_1")
        registrydecoder.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_1)
        self.toolBar_2 = QtGui.QToolBar(registrydecoder)
        self.toolBar_2.setObjectName("toolBar_2")
        registrydecoder.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_2)
        self.toolBar_3 = QtGui.QToolBar(registrydecoder)
        self.toolBar_3.setObjectName("toolBar_3")
        registrydecoder.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_3)
        self.statusbar = QtGui.QStatusBar(registrydecoder)
        self.statusbar.setObjectName("statusbar")
        registrydecoder.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(registrydecoder)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1197, 25))
        self.menuBar.setObjectName("menuBar")
        self.FileMenu = QtGui.QMenu(self.menuBar)
        self.FileMenu.setObjectName("FileMenu")
        self.menuActions = QtGui.QMenu(self.menuBar)
        self.menuActions.setObjectName("menuActions")
        registrydecoder.setMenuBar(self.menuBar)
        self.actionOpen_Case = QtGui.QAction(registrydecoder)
        self.actionOpen_Case.setObjectName("actionOpen_Case")
        self.actionSave_Case = QtGui.QAction(registrydecoder)
        self.actionSave_Case.setObjectName("actionSave_Case")
        self.actionClose_Case = QtGui.QAction(registrydecoder)
        self.actionClose_Case.setObjectName("actionClose_Case")
        self.actionExit = QtGui.QAction(registrydecoder)
        self.actionExit.setObjectName("actionExit")
        self.actionView = QtGui.QAction(registrydecoder)
        self.actionView.setObjectName("actionView")
        self.actionExport_Plugins = QtGui.QAction(registrydecoder)
        self.actionExport_Plugins.setObjectName("actionExport_Plugins")
        self.actionExport_Searches = QtGui.QAction(registrydecoder)
        self.actionExport_Searches.setObjectName("actionExport_Searches")
        self.actionBackup_Case = QtGui.QAction(registrydecoder)
        self.actionBackup_Case.setObjectName("actionBackup_Case")
        self.actionExport_Plugins_and_Searches = QtGui.QAction(registrydecoder)
        self.actionExport_Plugins_and_Searches.setObjectName("actionExport_Plugins_and_Searches")
        self.actionClose_Case_2 = QtGui.QAction(registrydecoder)
        self.actionClose_Case_2.setObjectName("actionClose_Case_2")
        self.toolBar_1.addSeparator()
        self.FileMenu.addAction(self.actionBackup_Case)
        self.FileMenu.addAction(self.actionClose_Case_2)
        self.FileMenu.addAction(self.actionExit)
        self.menuActions.addAction(self.actionExport_Plugins)
        self.menuActions.addAction(self.actionExport_Searches)
        self.menuActions.addAction(self.actionExport_Plugins_and_Searches)
        self.menuBar.addAction(self.FileMenu.menuAction())
        self.menuBar.addAction(self.menuActions.menuAction())

        self.retranslateUi(registrydecoder)
        self.stackedWidget.setCurrentIndex(0)
        self.analysisTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(registrydecoder)

    def retranslateUi(self, registrydecoder):
        registrydecoder.setWindowTitle(QtGui.QApplication.translate("registrydecoder", "Registry Decoder - Digital Forensics Solutions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("registrydecoder", "Registry Decoder Starting Page", None, QtGui.QApplication.UnicodeUTF8))
        self.startnewcase.setText(QtGui.QApplication.translate("registrydecoder", "Start a new case", None, QtGui.QApplication.UnicodeUTF8))
        self.loadexisting.setText(QtGui.QApplication.translate("registrydecoder", "Load an existing case", None, QtGui.QApplication.UnicodeUTF8))
        self.startPageButton.setText(QtGui.QApplication.translate("registrydecoder", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.loadCaseButton.setText(QtGui.QApplication.translate("registrydecoder", "Load Case", None, QtGui.QApplication.UnicodeUTF8))
        self.goBackPushButton.setText(QtGui.QApplication.translate("registrydecoder", "Back ", None, QtGui.QApplication.UnicodeUTF8))
        self.browseCaseButton.setText(QtGui.QApplication.translate("registrydecoder", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("registrydecoder", "Choose case directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("registrydecoder", "Case Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("registrydecoder", "Case Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("registrydecoder", "Investigator Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("registrydecoder", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("registrydecoder", "Case Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseCreateCase.setText(QtGui.QApplication.translate("registrydecoder", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.caseInformationButton.setText(QtGui.QApplication.translate("registrydecoder", "Create Case", None, QtGui.QApplication.UnicodeUTF8))
        self.goBackPushButton2.setText(QtGui.QApplication.translate("registrydecoder", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("registrydecoder", "Registry Types (Disk Images Only):", None, QtGui.QApplication.UnicodeUTF8))
        self.currentCheckBox.setText(QtGui.QApplication.translate("registrydecoder", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.backupCheckBox.setText(QtGui.QApplication.translate("registrydecoder", "Backups (System Restore)", None, QtGui.QApplication.UnicodeUTF8))
        self.addEvidenceButton.setText(QtGui.QApplication.translate("registrydecoder", "Add Evidence", None, QtGui.QApplication.UnicodeUTF8))
        self.doneEvidenceButton.setText(QtGui.QApplication.translate("registrydecoder", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.removeEvidenceButton.setText(QtGui.QApplication.translate("registrydecoder", "Remove Evidence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("registrydecoder", "Case Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.startProcessingButton.setText(QtGui.QApplication.translate("registrydecoder", "Start Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.backToAddEvidenceButton.setText(QtGui.QApplication.translate("registrydecoder", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("registrydecoder", "Registry Files", None, QtGui.QApplication.UnicodeUTF8))
        self.treeViewPushButton.setText(QtGui.QApplication.translate("registrydecoder", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTabWidget.setTabText(self.analysisTabWidget.indexOf(self.FileViewTab), QtGui.QApplication.translate("registrydecoder", "File View", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("registrydecoder", "Registry Files", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDiffTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("registrydecoder", "Compare File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("registrydecoder", "End Date", None, QtGui.QApplication.UnicodeUTF8))
        self.searchPushButton.setText(QtGui.QApplication.translate("registrydecoder", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("registrydecoder", "Start Date", None, QtGui.QApplication.UnicodeUTF8))
        self.partialSearchRadioButton.setText(QtGui.QApplication.translate("registrydecoder", "Partial Search", None, QtGui.QApplication.UnicodeUTF8))
        self.exactSearchRadioButton.setText(QtGui.QApplication.translate("registrydecoder", "Exact Search", None, QtGui.QApplication.UnicodeUTF8))
        self.searchKeysCheckBox.setText(QtGui.QApplication.translate("registrydecoder", "Keys", None, QtGui.QApplication.UnicodeUTF8))
        self.searchNamesCheckBox.setText(QtGui.QApplication.translate("registrydecoder", "Names", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDataCheckBox.setText(QtGui.QApplication.translate("registrydecoder", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("registrydecoder", "Search Terms (File)", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTermsPushButton.setText(QtGui.QApplication.translate("registrydecoder", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("registrydecoder", "Filter (mm/dd/yyyy)", None, QtGui.QApplication.UnicodeUTF8))
        self.performSearchDiffCheckBox.setText(QtGui.QApplication.translate("registrydecoder", "Perform Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTermLabel.setText(QtGui.QApplication.translate("registrydecoder", "Search Term", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTabWidget.setTabText(self.analysisTabWidget.indexOf(self.SearchTab), QtGui.QApplication.translate("registrydecoder", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginDiffTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("registrydecoder", "Compare File", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginFilestreeWidget.headerItem().setText(0, QtGui.QApplication.translate("registrydecoder", "Registry Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("registrydecoder", "Filter By Hive Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("registrydecoder", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginDiffCheckBox.setText(QtGui.QApplication.translate("registrydecoder", "Perform Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.runPluginButton.setText(QtGui.QApplication.translate("registrydecoder", "Run Plugin(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTabWidget.setTabText(self.analysisTabWidget.indexOf(self.PluginsTab), QtGui.QApplication.translate("registrydecoder", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_1.setWindowTitle(QtGui.QApplication.translate("registrydecoder", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("registrydecoder", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_3.setWindowTitle(QtGui.QApplication.translate("registrydecoder", "toolBar_3", None, QtGui.QApplication.UnicodeUTF8))
        self.FileMenu.setTitle(QtGui.QApplication.translate("registrydecoder", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("registrydecoder", "Reporting", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Case.setText(QtGui.QApplication.translate("registrydecoder", "Open Case", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Case.setText(QtGui.QApplication.translate("registrydecoder", "Save Case", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_Case.setText(QtGui.QApplication.translate("registrydecoder", "Close Case", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("registrydecoder", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView.setText(QtGui.QApplication.translate("registrydecoder", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Plugins.setText(QtGui.QApplication.translate("registrydecoder", "Export Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Searches.setText(QtGui.QApplication.translate("registrydecoder", "Export Searches", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup_Case.setText(QtGui.QApplication.translate("registrydecoder", "Backup Case", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Plugins_and_Searches.setText(QtGui.QApplication.translate("registrydecoder", "Export Plugins and Searches", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_Case_2.setText(QtGui.QApplication.translate("registrydecoder", "Close Case", None, QtGui.QApplication.UnicodeUTF8))

